# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      GITLAB_BASE_URL: ${{ vars.GITLAB_BASE_URL }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4', '8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.composer/cache/files
            ~/.cache/composer/files
          key: composer-${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-php-${{ matrix.php }}-
            composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Debug base URL
        run: |
          test -n "$GITLAB_BASE_URL" || (echo "GITLAB_BASE_URL fehlt" && exit 1)

      - name: Create coverage directory
        run: mkdir -p build/coverage

      - name: Run tests with coverage
        run: |
          vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --coverage-clover build/coverage/clover.xml \
            --coverage-html build/coverage/html \
            --coverage-text

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-php-${{ matrix.php }}
          path: build/coverage/


      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --configuration phpstan.neon.dist
